CREATE DATABASE NOZAMA 

CREATE TABLE USER (
    UserID INT PRIMARY KEY IDENTITY(1,1),
    FirstName NVARCHAR(100) NOT NULL,
    LastName NVARCHAR(100) NOT NULL,
    [Password] NVARCHAR(50) NOT NULL,
    Email NVARCHAR(255) NOT NULL
);

CREATE TABLE BRAND (
    BrandID INT PRIMARY KEY IDENTITY(1,1),
    [Name] NVARCHAR(100) NOT NULL
);

CREATE TABLE CATEGORY (
    CategoryID INT PRIMARY KEY IDENTITY(1,1),
    [Name] NVARCHAR(100) NOT NULL
);

CREATE TABLE PRODUCT (
    ProductID INT PRIMARY KEY IDENTITY(1,1),
    ProductName NVARCHAR(100) NOT NULL,
    [Description] NVARCHAR(500) NOT NULL,
    Specification NVARCHAR(50) NOT NULL,
    Stock INT NOT NULL,
    BasePrice DECIMAL(18,2) NOT NULL,
    DiscountPercentage DECIMAL(9,2) NOT NULL,
    ImgURL NVARCHAR(MAX) NOT NULL,
    CategoryID INT NOT NULL,
    BrandID INT NOT NULL,
    CONSTRAINT FK_CategoryID FOREIGN KEY (CategoryID) REFERENCES CATEGORY(CategoryID),
    CONSTRAINT FK_BrandID FOREIGN KEY (BrandID) REFERENCES BRAND(BrandID)
);

CREATE TABLE SHOPPING_CART (
    UserID INT PRIMARY KEY NOT NULL,
    ProductID INT PRIMARY KEY NOT NULL,
    Amount INT NOT NULL,
    CONSTRAINT PK_ShoppingCart PRIMARY KEY (UserID, ProductID)
    CONSTRAINT FK_UserID FOREIGN KEY (UserID) REFERENCES USER(UserID),
    CONSTRAINT FK_ProductID FOREIGN KEY (ProductID) REFERENCES PRODUCT(ProductID)
);

CREATE TABLE ProductRating (
    RatingID INT PRIMARY KEY IDENTITY(1,1),
    ProductID INT NOT NULL,
    UserID INT NOT NULL,
    Review NVARCHAR(1000) DEFAULT '',
    Rating INT NOT NULL,
    [DateTime] DATETIME DEFAULT GETDATE(),
    CONSTRAINT FK_ProductID FOREIGN KEY (ProductID) REFERENCES PRODUCT(ProductID),
    CONSTRAINT FK_UserID FOREIGN KEY (UserID) REFERENCES USER(UserID)
);

CREATE TABLE [ORDER] (
    OrderID INT IDENTITY(1,1) PRIMARY KEY,
    UserID INT NOT NULL,
    DateTime DATETIME NOT NULL,
    [Status] NVARCHAR(1) NOT NULL,
    [Location] NVARCHAR(255) NOT NULL,
    CONSTRAINT FK_UserID FOREIGN KEY (UserID) REFERENCES USER(UserID)
);

CREATE TABLE ORDER_LINE (
    OrderID INT NOT NULL,
    [Line] INT NOT NULL,
    ProductID INT NOT NULL,
    Amount INT NOT NULL,
    CONSTRAINT PK_ORDER_LINE PRIMARY KEY (OrderID, [Line]),
    CONSTRAINT FK_ProductID FOREIGN KEY ProductID REFERENCES PRODUCT(ProductID),
    CONSTRAINT FK_ORDER_ID FOREIGN KEY OrderID REFERENCES [ORDER](OrderID)
);

CREATE TABLE BILL (
    BillID INT IDENTITY(1,1) PRIMARY KEY,
    OrderID INT NOT NULL,
    PSumTotal DECIMAL(18,2) NOT NULL,
    DeliveryFee DECIMAL(18,2) NOT NULL,
    Total DECIMAL(18,2) NOT NULL,
    PaymentMethod NVARCHAR(100) NOT NULL,
    DateTime DATETIME NOT NULL,
    Status NVARCHAR(1) NOT NULL,
    CONSTRAINT FK_Order FOREIGN KEY (OrderID) REFERENCES ORDERS(OrderID)
);


